### ISSUE TITLE
Adsorption parameters

### ISSUE THREAD

**Issue by drpengyuhuang** [UnconvRS/shale#4]
Dear all,

I tried to use the adsorption function in the modules called "shale". I am a bit confused about the input parameters for the shale adsorption. In the function "getShaleCompFluidCase()", the comments says that "%Pressure in Pa in first column, rho_sL in kg/m^3 in 2nd column" for the isotherm parameters. I wonder what "rho_sL" is in this case. Usually a Langmuir isotherm is used, and the two parameters are Langmuir pressure and Langmuir volume. May I ask what the definitions of the isotherm parameters are? since I could not find a reference about them. Thank you.

Regards,
Pengyu

**Comment by UnconvRS** [comment]
We typically use Langmuir pressure and volume in petroleum engineering, but we had to convert the function to work with SI units, which is the default units used in MRST. There are several equivalent forms of representing Langmuir isotherm, and one of those involves the use of  "rho_sL" (which is the maximum mass density of the gas that can be sorbed in the reservoir rock) instead of Langmuir Volume, and "rho_s" in place of "V_s".

Further details on sorption and other functionalities of the "shale" module are provided in Chapter 10 of the "Advanced Modeling with the MRST", which will be published later this year.

**Comment by drpengyuhuang** [comment]
Thank you for your reply, Professor Olorode. I have tried to find a type of Langmuir isotherm equation that is expressed as a function of pressure and maximum mass density of gas from literature, but I still could not find it. If possible, can you provide me a reference for that equation? I want to convert the Langmuir volume and pressure parameters into the adsorption parameters used in your codes and MRST codes. It may take a long time to wait for the new MRST book to be published. Many thanks!

**Comment by UnconvRS** [comment]
I checked and realized that I just have the variants of the Langmuir equation from a slide in a course I took in the past. I recall seeing some of those variants in a paper but I couldn't find it. That said, those variants don't show you how to go from one unit to another, and I had to go through the unit conversions myself. I will share one of those hand derivations via email.

**Comment by drpengyuhuang** [comment]
Thank you!
