### ISSUE TITLE
Upscaling the EagleFord example

### ISSUE THREAD

**Issue by kiauho** [UnconvRS/shale#8]
Hi Professor Olorode,

The EagleFord example shows a representative model for one stage and local grid refinement is used to model that one stage.  The model takes a few hours to run.  I wonder what is the strategy to upscale the model for 20 stages.  Would the linear equation solver be able to handle that many grid cells?

Look forward to your guidance.

Best regards,

David

**Comment by UnconvRS** [comment]
Hi David,

It will be very computationally expensive to run the full system, but you don't need to do this because of symmetry. What is modeled in the EagleFord.m case is the smallest repeating element, which is called a stencil. So, to get the result for a system of 20 stages, you will need to multiply the production from this stencil by 80, because the stencil is half of the thickness of the reservoir and models half of the fracture length.

**Comment by UnconvRS** [comment]
I also just realized that the Advanced Modeling with MRST book is out. Section 10.6.1 explains the stencil representation, and how to scale it up to the full reservoir.

**Comment by UnconvRS** [comment]
Here is the link to the book which can be downloaded freely: https://www.cambridge.org/core/books/advanced-modeling-with-the-matlab-reservoir-simulation-toolbox/7AC2425C73F6F729DB88DB1A504FA1E7

**Comment by kiauho** [comment]
Thank your Professor Olorode for the insights on the upscaling.  Will do some history match with the actual data to learn more about all the parameters involved.  Also thanks for the newly published book.  It will be my book to read over the holidays.  Have wonderful holidays.
